config/routes.rb
Icebound2::Application.routes.draw do
  root :to => "home#index"
  resources :users, :only => [:index, :show, :edit, :update ]
  match '/auth/:provider/callback' => 'sessions#create'
  match '/signin' => 'sessions#new', :as => :signin
  match '/signout' => 'sessions#destroy', :as => :signout
  match '/signout/done' => 'home#auth_failure', :as => :signout_done
  match '/auth/failure' => 'sessions#failure'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/manuscript.rb
class Manuscript < ActiveRecord::Base
  belongs_to :manuscript_type
  belongs_to :user
end

app/models/manuscript_type.rb
class ManuscriptType < ActiveRecord::Base
  has_many :manuscripts
  belongs_to :user
end

app/models/market.rb
class Market < ActiveRecord::Base
  belongs_to :market_type
  belongs_to :user
end

app/models/market_type.rb
class MarketType < ActiveRecord::Base
  has_many :markets
  belongs_to :user
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  attr_accessible :role_ids, :as => :admin
  attr_accessible :provider, :uid, :name, :email

  has_many :markets
  has_many :market_types
  has_many :manuscript_types
  has_many :manuscripts

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      if auth['info']
         user.name = auth['info']['name'] || ""
         user.email = auth['info']['email'] || ""
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Exception => e
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = User.find(params[:id])
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end


  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :check_session!, :except => [:auth_failure]

  def check_session!
    redirect_to '/auth/google_oauth2' unless user_signed_in?
  end

  def carousel_group_count
    3
  end

  def index
    @grouped_markets = Market.where(["user_id =?", current_user ]).in_groups_of(carousel_group_count)
    @manuscripts = Manuscript.where(["user_id =?", current_user ]).page(params[:page] || 1)
  end

  def auth_failure
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    redirect_to '/auth/google_oauth2'
  end


  def create
    auth = request.env["omniauth.auth"]
    user = User.where(:provider => auth['provider'], 
                      :uid => auth['uid'].to_s).first || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    user.add_role :admin if User.count == 1 # make the first user an admin
    if user.email.blank?
      redirect_to edit_user_path(user), :alert => "Please enter your email address."
    else
      redirect_to root_url, :notice => 'Signed in!'
    end

  end

  def destroy
    reset_session
    redirect_to signout_done_path, :notice => 'Signed out!'
  end

  def failure
    redirect_to root_url, :alert => "Authentication error: #{params[:message].humanize}"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :correct_user?, :except => [:index]

  def index
    @users = User.all
  end

    def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to @user
    else
      render :edit
    end
  end


def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/auth_failure.html.erb
<p>Login in to use the submission tracker.</p>

app/views/home/index.html.erb
<h3>Home</h3>
<div class="span11 well">
  <h4>Current</h4>
</div>
<div class="span11 well container-fluid">
  <h4>Manuscripts</h4>


  <div class="row-fluid">
    <div id="manuscriptCarousel">
      <div id="manuscript_paginator">
        <%= paginate @manuscripts, :remote => true  %>
      </div>
      <div id="manuscripts" class="row-fluid">
        <p> something is here.</p>
         <%= render @manuscripts%>
      </div>
    </div>
  </div>
</div>
<div class="span11 well">
  <h4>Markets</h4>

  <div class="row-fluid">
    <div id="marketCarousel" class="carousel slide" data-interval='false'>
      <!-- Carousel items -->
      <div class="carousel-inner">
        <% first = 'active ' %>
        <% @grouped_markets.each do |group| %>
            <div class="<%= first %>item">
              <% group.each do |market| %>
                  <% if market %>
                      <div class="itemCell span2 has_popover" data-html="true" title='<%= market.name %>' data-trigger='hover' data-content="<p>Type: <%= market.market_type.name %></p><p>Email: <%= market.email %><p>website: <%= "<a href='#{market.website}' target='_new'>#{market.website}</a>" %></p>">
                        <%= market.name if market %>
                      </div>
                  <% end %>
              <% end %>
            </div>
            <% first = '' %>
        <% end %>

      </div>
      <!-- Carousel nav -->
      <a class="carousel-control left" href="#marketCarousel" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#marketCarousel" data-slide="next">&rsaquo;</a>
    </div>
  </div>
</div>
<div class="span11 well">
  <h4>Submissions</h4>
</div>

app/views/home/index.js.erb
$('#manuscripts').html('<%= escape_javascript render(@manuscripts) %>');
$('#manuscript_paginator').html('<%= escape_javascript(paginate(@manuscripts, :remote => true).to_s) %>');

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Icebound2", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', signout_path %>      
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', signin_path %> 
    </li>
  <% end %>
  <% if user_signed_in? %>
    <% if current_user.has_role? :admin %>
      <li>
      <%= link_to 'Admin', users_path %>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Icebound2" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Icebound2" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/manuscripts/_manuscript.html.erb
<div class="itemCell span2 has_popover" data-html="true" title='<%= manuscript.title %>' data-trigger='hover' data-placement='bottom' data-content="<p>Type: <%= manuscript.manuscript_type.name %></p><p>Word Count: <%= manuscript.word_count %></p>">
  <%= manuscript.title %>
</div>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br />
  <%= f.submit "Sign in" %>
<% end %>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>                                      
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>